In [1]:
import time
import numpy as np
import pandas as pd

from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.model_selection import cross_val_score
from xgboost.sklearn import XGBClassifier

from tianchi.user_location_prediction.pysrc.construct_train_test_data import DataGenerator

/home/zhouzr/anaconda3/lib/python3.6/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [2]:
def cv_test(x, y, cv, model):
    t = time.time()
    result = np.array(cross_val_score(model, x, y, cv=cv, scoring='accuracy', n_jobs=-1))
    t_use = (time.time()-t) / 60 / cv
    print('per cv cost:%.2f min'%(t_use))
    return result

In [3]:
data_generator = DataGenerator()

/home/zhouzr/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2881: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)


In [7]:
feat_all = ['weekday' ,'hour' ,'holiday', 'space_loc','space_dist','wifi_power','wifi_power_dist',
            'wifi_flag','wifi_flag_dist','user_cate','user_price']
feat_submission_1 = ['weekday' ,'hour' , 'space_loc','wifi_power','wifi_flag']
feat_submission_2 = ['weekday' ,'hour' , 'space_loc','space_dist','wifi_power','wifi_power_dist',
            'wifi_flag','wifi_flag_dist']
feat_submission_3 = ['weekday' ,'hour','holiday' , 'space_loc','wifi_power','wifi_flag','user_cate','user_price']

In [8]:
mall_id = 'm_7800'

### all feat

In [9]:
train_x, train_y, test_x, test_row_id = data_generator.gen_sub_train_test_data(feat_all, mall_id)
feat1_lr_score = cv_test(train_x, train_y, 5, LogisticRegression())
print(feat1_lr_score)
print(feat1_lr_score.mean())

/home/zhouzr/anaconda3/lib/python3.6/site-packages/sklearn/model_selection/_split.py:581: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of groups for any class cannot be less than n_splits=5.
  % (min_groups, self.n_splits)), Warning)


per cv cost:0.86 min
[ 0.79824341  0.78971256  0.79158215  0.78665988  0.7943208 ]
0.792103759118


### submission 1 LB score 0.84

In [10]:
train_x, train_y, test_x, test_row_id = data_generator.gen_sub_train_test_data(feat_submission_1, mall_id)
feat1_lr_score = cv_test(train_x, train_y, 5, LogisticRegression())
print(feat1_lr_score)
print(feat1_lr_score.mean())

/home/zhouzr/anaconda3/lib/python3.6/site-packages/sklearn/model_selection/_split.py:581: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of groups for any class cannot be less than n_splits=5.
  % (min_groups, self.n_splits)), Warning)


per cv cost:0.19 min
[ 0.63086575  0.62581947  0.6214503   0.62194501  0.62420056]
0.624856217851


#### submission 2  LB score 0.85

In [11]:
train_x, train_y, test_x, test_row_id = data_generator.gen_sub_train_test_data(feat_submission_2, mall_id)
feat1_lr_score = cv_test(train_x, train_y, 5, LogisticRegression())
print(feat1_lr_score)
print(feat1_lr_score.mean())

/home/zhouzr/anaconda3/lib/python3.6/site-packages/sklearn/model_selection/_split.py:581: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of groups for any class cannot be less than n_splits=5.
  % (min_groups, self.n_splits)), Warning)


per cv cost:0.62 min
[ 0.63563363  0.63161876  0.6234787   0.62372709  0.62906114]
0.628703863182


### submission 3

In [12]:
train_x, train_y, test_x, test_row_id = data_generator.gen_sub_train_test_data(feat_submission_3, mall_id)
feat1_lr_score = cv_test(train_x, train_y, 5, LogisticRegression())
print(feat1_lr_score)
print(feat1_lr_score.mean())

/home/zhouzr/anaconda3/lib/python3.6/site-packages/sklearn/model_selection/_split.py:581: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of groups for any class cannot be less than n_splits=5.
  % (min_groups, self.n_splits)), Warning)


per cv cost:0.35 min
[ 0.795734    0.78593041  0.78727181  0.78233198  0.79150678]
0.788554994209
